### PR TITLE
intersphinx_mapping

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
**~Dependency on `catkin_tools` should be bumped to `>=0.7.2` after https://github.com/catkin/catkin_tools/pull/691 has been merged and released~**

**~Dependency on `sphinx` should be bumped to `>=4.3.0` after https://github.com/sphinx-doc/sphinx/pull/9685 has been merged(done) and released~**

~This PR is WIP, but I have some issues to discuss.~

I have figuted out how the `intersphinx_mapping` should look like, it should look the following:
```
{'PKG_NAME': ('RELATIVE_PATH_OF_OBJECTS_INV_DIR_TO_CONF_DIR', None)}
```
The `None` can be replace by an other location of the `objects.inv` file, if it isn't in the base dir.

First issue, the `objects.inv` is located at `WS/docs/PKG_NAME/html/OPTIONAL_OUTPUT_DIR/objects.inv`. So that requires parsing the `package.xml` and `rosdoc.yaml` of other packages IMO. This brings the issue that we need to determine the root dir of the packages in the `src` folder.

Second issue: The deps that are passed to the `sphinx` function are only the deps that are being build. So with `--no-deps` this is empty. Therefore it is unwanted to use this list to fill the `intersphinx_mapping`. Another solution could be to just fill the mapping with all packages that have an `objects.inv` file.

Please let me know what you think.

P.S.
This PR requires https://github.com/sphinx-doc/sphinx/pull/9685. Because right now, intersphinx can't handle relative uri correctly. Which I think is the only to do this. As it allows the docs to used locally, but also in a hosted situation like github pages.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
I think there is no alternative for the first issue. In case you only want to fill the `intersphinx_mapping` with the dependencies, you should parse the `rosdoc` config file of the dependencies.

For the second issue: Doxygen has the same problem right now, in case you run with `--no-deps` it doesn't generate any references to depedencies. We could add an extra argument to the builder functions, which contains just all dependencies in the workspace. lets call them `reference_deps` or similar.

An alternative solution which fixes both issues, is to just look for `objects.inv` files for sphinx and `tags` files for doxygen. As the path of these files is not fixed, a glob search would be needed. Which could be slower.

I prefer to not go for the alternative solution. @mikepurvis what do you think?

**Comment by mikepurvis** [comment]
So the history here is that this plugin was thrown together in haste to meet documentation needs at Clearpath— doc builds were the last thing still running on our ros_buildfarm instance, and for a variety of reasons we really needed to get it shut down. We've always rebuilt all the docs for everything in one mega nightly build, so no effort at all was put (by us, anyway) into making the doc builds incremental or overlay-able, or any of that.

I'd love to see these improvements land, but as far as the more medium-term future, I'm looking at this point to actually migrate this to a colcon plugin, and colcon's architecture is such that there's much less of a divide between a package built as a one-off vs in a larger workspace— the whole thing is way more uniform in that regard. So I'm definitely interested in a solution that can do discovery based on existing installspaces rather than it being special in-Python magic to make it happen.

**Comment by MatthijsBurgh** [comment]
@mikepurvis have you been able to take a look at this?

**Comment by MatthijsBurgh** [comment]
@mikepurvis friendly ping ;)

**Comment by MatthijsBurgh** [comment]
@mikepurvis friendly ping ;)

**Comment by mikepurvis** [comment]
Looks great! I haven't actually tried it out, but can you describe what your testing/validation process has been for this?

Also, looks like we're still blocked on a catkin_tools merge/release and possibly a Sphinx release also?

**Comment by MatthijsBurgh** [comment]
For the releases, both `catkin_tools` and `sphinx` have been released with the required patches.

I have run many different runs on my own workspace.
- Run on the entire workspace.
- Run on a single package
- Run on a single package with `--no-deps`
- Run on multiple packages
- Run on multiple packages with `--no-deps`

Workspace contains both sphinx and doxygen documentation, so also the changes regarding the doxygen paths is tested.

For the runs of `--no-deps` it is still possible to find `objects.inv` files of other packages from previous runs. So generating docs of a single packages, doesn't break the referencing.

**Comment by mikepurvis** [comment]
Great, sounds awesome!

**Comment by MatthijsBurgh** [comment]
@mikepurvis could you create a new release please?

**Pull request merged**
